{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (ne (include "loki-vl-proxy.workloadKind" .) "StatefulSet") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loki-vl-proxy.persistenceClaimName" . }}
  labels:
    {{- include "loki-vl-proxy.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
