package logql

// Queries Loki v3.7.7 accepts for a log range with parentheses, an offset, an
// unwrap on either side of the range, a pipeline after the range, and line
// filters with `or` alternatives (syntax.y logRangeExpr, lineFilter, orFilter).
// Each one was run against Loki 3.7.7 and answered 200.
var lokiAcceptedLogRanges = []string{
	"rate({app=\"x\"}[5m])",
	"rate({app=\"x\"}[5m] offset 1h)",
	"rate(({app=\"x\"})[5m])",
	"rate(({app=\"x\"})[5m] offset 1h)",
	"rate((({app=\"x\"})[5m]))",
	"rate(((({app=\"x\"})[5m])))",
	"rate(({app=\"x\"}[5m]))",
	"rate((({app=\"x\"}[5m])))",
	"rate({app=\"x\"} | json [5m])",
	"rate(({app=\"x\"} | json)[5m])",
	"rate(({app=\"x\"} | json)[5m] offset 5m)",
	"rate(({app=\"x\"} | json [5m]))",
	"rate({app=\"x\"}[5m] | json)",
	"rate({app=\"x\"}[5m] offset 5m | json)",
	"rate(({app=\"x\"}[5m] | json))",
	"rate({app=\"x\"}[5m] |= \"a\" |= \"b\")",
	"sum_over_time({app=\"x\"} | json | unwrap v [5m])",
	"sum_over_time({app=\"x\"} | json | unwrap v [5m] offset 1m)",
	"sum_over_time(({app=\"x\"} | json | unwrap v)[5m])",
	"sum_over_time(({app=\"x\"} | json | unwrap v)[5m] offset 1m)",
	"sum_over_time((({app=\"x\"} | json | unwrap v)[5m]))",
	"sum_over_time(({app=\"x\"} | json | unwrap v [5m]))",
	"sum_over_time({app=\"x\"} | unwrap v [5m])",
	"sum_over_time({app=\"x\"}[5m] | unwrap v)",
	"sum_over_time({app=\"x\"}[5m] offset 1m | unwrap v)",
	"sum_over_time({app=\"x\"}[5m] | json | unwrap v)",
	"sum_over_time({app=\"x\"}[5m] offset 1m | json | unwrap v)",
	"sum_over_time(({app=\"x\"})[5m] | unwrap v)",
	"sum_over_time(({app=\"x\"})[5m] offset 1m | unwrap v)",
	"sum_over_time(({app=\"x\"} | unwrap v)[5m])",
	"sum_over_time(({app=\"x\"}[5m] | unwrap v))",
	"sum_over_time(({app=\"x\"}[5m] | json | unwrap v))",
	"sum_over_time(({app=\"x\"} | json | unwrap bytes(v))[5m])",
	"sum_over_time(({app=\"x\"} | json | unwrap v | v > 5)[5m])",
	"quantile_over_time(0.5, ({app=\"x\"} | json | unwrap v)[5m])",
	"quantile_over_time(0.5, ({app=\"x\"} | json | unwrap v)[5m]) by (a)",
	"quantile_over_time(0.5, {app=\"x\"}[5m] | json | unwrap v)",
	"sum by (a) (rate(({app=\"x\"} |= \"e\")[5m]))",
	"sum by (a) (rate(({app=\"x\"} |= \"e\")[5m])) / sum by (a) (rate(({app=\"x\"})[5m]))",
	"rate(({app=\"x\"} |= \"e\")[5m]) > 0",
	"topk(3, sum by (a) (count_over_time(({app=\"x\"} |= \"e\")[5m])))",
	"rate(({app=\"x\"} |= \"e\" or \"f\")[5m])",
	"absent_over_time(({app=\"x\"} |= \"e\")[5m])",
	"bytes_over_time(({app=\"x\"} |= \"e\")[5m])",
	"bytes_rate(({app=\"x\"} |= \"e\")[5m])",
	"first_over_time(({app=\"x\"} | json | unwrap v)[5m])",
	"rate((({app=\"x\"} |= \"e\")[5m] offset 1m))",
	"rate(({app=\"x\"} |= \"e\") [5m])",
	"({app=\"x\"} |= \"a\")",
	"(({app=\"x\"} |= \"a\"))",
	"((({app=\"x\"})))",
	"({app=\"x\"} | json | v > 1)",
	"{app=\"x\"} |= \"a\" or \"b\"",
	"{app=\"x\"} |= \"a\" or \"b\" or \"c\"",
	"{app=\"x\"} |= `a` or `b`",
	"{app=\"x\"} |= \"a\" or `b`",
	"{app=\"x\"} |= \"a\" or ip(\"1.2.3.4\")",
	"{app=\"x\"} |= \"a\" or ip(\"1.2.3.4\") or \"b\"",
	"{app=\"x\"} |= ip(\"1.2.3.4\") or \"b\"",
	"{app=\"x\"} |= ip(\"1.2.3.4\") or ip(\"5.6.7.8\")",
	"{app=\"x\"} |= \"a\" or ip(\"1.2.3.4\") or ip(\"5.6.7.8\")",
	"{app=\"x\"} != \"a\" or ip(\"1.2.3.4\")",
	"{app=\"x\"} != ip(\"1.2.3.4\") or \"a\"",
	"{app=\"x\"} |~ \"a\" or ip(\"1.2.3.4\")",
	"{app=\"x\"} |> \"<_>a\" or ip(\"1.2.3.4\")",
	"{app=\"x\"} |= \"a\" or ip(\"999.1.1.1\")",
	"{app=\"x\"} |~ \"a\" or \"b\" |~ \"c\" or \"d\"",
	"{app=\"x\"} |= \"a\" or \"b\" | json",
	"{app=\"x\"} |= \"a\" or \"b\" | json | x=\"1\"",
	"{app=\"x\"} |= \"a\" or \"b\" != \"z\" or \"y\" |~ \"q\"",
	"{app=\"x\"} |> \"<_>a\" or \"<_>b\" or \"<_>c\"",
	"{app=\"x\"} !> \"<_>a\" or \"<_>b\"",
	"{app=\"x\"} |> \"a <_> b\" or \"c <_>\"",
	"{app=\"x\"} |> \"(\" or \"a\"",
	"{app=\"x\"} |= \"a\" or \"b\" or \"c\" or \"d\" or \"e\"",
	"{app=\"x\"} |= \"\" or \"b\"",
	"{app=\"x\"} |~ \"\" or \"b\"",
	"rate({app=\"x\"} |= \"a\" or \"b\" [5m])",
	"rate({app=\"x\"} != \"a\" or \"b\" [5m])",
	"count_over_time({app=\"x\"} |~ \"a\" or \"b\" | json [5m])",
	"sum_over_time({app=\"x\"} |= \"a\" or \"b\" | json | unwrap v [5m])",
	"{app=\"x\"} | json |= \"a\" or \"b\"",
	"{app=\"x\"} | logfmt != \"a\" or \"b\"",
	"{app=\"x\"} | line_format \"{{.a}}\" |= \"a\" or \"b\"",
	"{app=\"x\"} | json | x=\"1\" |= \"a\" or \"b\"",
	"{app=\"x\"} |> \"(\" ",
}

// Queries Loki rejects, with the error text Loki v3.7.7 returned.
var lokiRejectedLogRanges = []struct{ query, want string }{
	{"rate((({app=\"x\"} | json))[5m])", "parse error at line 1, col 25: syntax error: unexpected ), expecting RANGE"},
	{"rate(({app=\"x\"})[5m] | json)", "parse error at line 1, col 24: syntax error: unexpected json, expecting unwrap"},
	{"rate(({app=\"x\"} |= \"a\")[5m] |= \"b\")", "parse error at line 0, col 29: syntax error: unexpected |=, expecting )"},
	{"rate({app=\"x\"} |= \"a\" [5m] |= \"b\")", "parse error at line 0, col 28: syntax error: unexpected |=, expecting )"},
	{"sum_over_time(({app=\"x\"}[5m]) | unwrap v)", "parse error at line 1, col 31: syntax error: unexpected |, expecting )"},
	{"sum_over_time(({app=\"x\"} | json)[5m] | unwrap v)", "parse error at line 1, col 38: syntax error: unexpected |, expecting )"},
	{"sum_over_time(({app=\"x\"} | json) | unwrap v [5m])", "parse error at line 1, col 34: syntax error: unexpected |, expecting RANGE"},
	{"rate((({app=\"x\"} |= \"e\"))[5m])", "parse error at line 1, col 25: syntax error: unexpected ), expecting RANGE"},
	{"rate(({app=\"x\"} |= \"e\")[5m]))", "parse error at line 1, col 29: syntax error: unexpected )"},
	{"rate((({app=\"x\"} |= \"e\")[5m])", "parse error at line 1, col 30: syntax error: unexpected $end, expecting )"},
	{"rate((({app=\"x\"} |= \"e\")[5m]) offset 1m)", "parse error at line 1, col 31: syntax error: unexpected offset, expecting )"},
	{"rate(({app=\"x\"} |= \"e\")[5m][1m])", "parse error at line 0, col 28: syntax error: unexpected RANGE, expecting )"},
	{"rate(({app=\"x\"} |= \"e\"))", "parse error at line 1, col 24: syntax error: unexpected ), expecting RANGE"},
	{"rate(({app=\"x\"} |= \"e\")[5m] by (a))", "parse error at line 1, col 29: syntax error: unexpected by, expecting )"},
	{"({app=\"x\"}) |= \"a\"", "parse error at line 0, col 13: syntax error: unexpected |="},
	{"({app=\"x\"} |= \"a\") |= \"b\"", "parse error at line 0, col 20: syntax error: unexpected |="},
	{"({app=\"x\"} |= \"a\"", "parse error at line 1, col 18: syntax error: unexpected $end"},
	{"{app=\"x\"} |= \"a\")", "parse error at line 1, col 17: syntax error: unexpected )"},
	{"()", "parse error at line 1, col 2: syntax error: unexpected )"},
	{"({app=\"x\"} | json) | v > 1", "parse error at line 1, col 20: syntax error: unexpected |"},
	{"{app=\"x\"} |= \"a\" or", "parse error at line 1, col 20: syntax error: unexpected $end, expecting STRING or ip"},
	{"{app=\"x\"} |= \"a\" or \"b\" or", "parse error at line 1, col 27: syntax error: unexpected $end, expecting STRING or ip"},
	{"{app=\"x\"} |= or \"b\"", "parse error at line 1, col 14: syntax error: unexpected or, expecting STRING or ip"},
	{"{app=\"x\"} |= \"a\" or or \"b\"", "parse error at line 1, col 21: syntax error: unexpected or, expecting STRING or ip"},
	{"{app=\"x\"} |= \"a\" and \"b\"", "parse error at line 1, col 22: syntax error: unexpected STRING"},
	{"{app=\"x\"} |= \"a\" or (\"b\")", "parse error at line 1, col 21: syntax error: unexpected (, expecting STRING or ip"},
	{"{app=\"x\"} !~ \"a\" or ip(\"1.2.3.4\")", "parse error : stage '!~ \"a\" !~ ip(\"1.2.3.4\")' : ip: invalid operation"},
	{"{app=\"x\"} |= \"a\" or ip(1)", "parse error at line 1, col 24: syntax error: unexpected NUMBER, expecting STRING"},
	{"{app=\"x\"} |~ \"a\" or \"(\"", "parse error : stage '|~ \"a\" or \"(\"' : error parsing regexp: missing closing ): `(`"},
	{"{app=\"x\"} |~ \"(\" or \"a\"", "parse error : stage '|~ \"(\" or \"a\"' : error parsing regexp: missing closing ): `(`"},
	{"{app=\"x\"} |= \"a\" or \"b\" [5m]", "parse error at line 0, col 25: syntax error: unexpected RANGE"},
	{"{app=\"x\"} |~ \"(\"", "parse error : stage '|~ \"(\"' : error parsing regexp: missing closing ): `(`"},
	{"{app=\"x\"} !~ \"(\"", "parse error : stage '!~ \"(\"' : error parsing regexp: missing closing ): `(`"},
	{"{app=\"x\"} !~ \"a\" or \"(\"", "parse error : stage '!~ \"a\" !~ \"(\"' : error parsing regexp: missing closing ): `(`"},
	{"{app=\"x\"} !> \"a\" or ip(\"1.1.1.1\")", "parse error : stage '!> \"a\" !> ip(\"1.1.1.1\")' : ip: invalid operation"},
	{"{app=\"x\"} != \"a\" or ip(\"999.1.1.1\")", "parse error : stage '!= \"a\" != ip(\"999.1.1.1\")' : ip: invalid pattern: \"999.1.1.1\""},
	{"{app=\"x\"} |~ \"a\" or \"(\" or \"b\"", "parse error : stage '|~ \"a\" or \"(\" or \"b\"' : error parsing regexp: missing closing ): `(`"},
}
