package logsql

import "testing"

// TestMarkerMethods explicitly invokes every Go-interface marker method on the
// AST types in this package. The methods are unexported empty stubs that exist
// only to satisfy interface type discrimination — Go's coverage counter treats
// each as a real function with one statement, so they have to be exercised
// from inside the package (external _test.go cannot reach them).
//
// There is no behaviour to assert; the test passes as long as it compiles and
// the calls panic-free.
func TestMarkerMethods(t *testing.T) {
	// Query implements Expr.
	Query{}.expr()
	DeferredExpr{}.expr()
	DeferredExpr{}.filterExpr()
	DeferredExpr{}.statsFunc()

	// FilterExpr implementors.
	Word{}.filterExpr()
	Phrase{}.filterExpr()
	Prefix{}.filterExpr()
	Substring{}.filterExpr()
	Exact{}.filterExpr()
	Regexp{}.filterExpr()
	Sequence{}.filterExpr()
	CaseInsensitive{}.filterExpr()
	Wildcard{}.filterExpr()
	FieldFilter{}.filterExpr()
	StreamFilter{}.filterExpr()
	TimeFilter{}.filterExpr()
	AndExpr{}.filterExpr()
	OrExpr{}.filterExpr()
	NotExpr{}.filterExpr()
	AnyCasePhrase{}.filterExpr()
	AnyCasePrefix{}.filterExpr()
	ExactPrefix{}.filterExpr()
	ContainsAll{}.filterExpr()
	ContainsAny{}.filterExpr()
	DayRange{}.filterExpr()
	WeekRange{}.filterExpr()
	LenRange{}.filterExpr()
	PatternMatch{}.filterExpr()

	// Pipe implementors.
	PipeUnpackJSON{}.pipe()
	PipeFilter{}.pipe()
	PipeLimit{}.pipe()
	PipeUnpackLogfmt{}.pipe()
	PipeExtract{}.pipe()
	PipeExtractRegexp{}.pipe()
	PipeFields{}.pipe()
	PipeDelete{}.pipe()
	PipeFormat{}.pipe()
	PipeRename{}.pipe()
	PipeReplace{}.pipe()
	PipeReplaceRegexp{}.pipe()
	PipePackJSON{}.pipe()
	PipePackLogfmt{}.pipe()
	PipeStats{}.pipe()
	PipeMath{}.pipe()
	PipeSort{}.pipe()
	PipeTop{}.pipe()
	PipeFirst{}.pipe()
	PipeLast{}.pipe()
	PipeSample{}.pipe()
	PipeOffset{}.pipe()
	PipeUniq{}.pipe()
	PipeFieldNames{}.pipe()
	PipeDropEmptyFields{}.pipe()
	PipeCopy{}.pipe()
	PipeCoalesce{}.pipe()
	PipeCollapseNums{}.pipe()
	PipeDecolorize{}.pipe()
	PipeFacets{}.pipe()
	PipeFieldValues{}.pipe()
	PipeGenerateSequence{}.pipe()
	PipeHash{}.pipe()
	PipeJoin{}.pipe()
	PipeJSONArrayLen{}.pipe()
	PipeLen{}.pipe()
	PipeQueryStats{}.pipe()
	PipeRunningStats{}.pipe()
	PipeSetStreamFields{}.pipe()
	PipeSplit{}.pipe()
	PipeStreamContext{}.pipe()
	PipeTimeAdd{}.pipe()
	PipeTotalStats{}.pipe()
	PipeUnion{}.pipe()
	PipeUnpackSyslog{}.pipe()
	PipeUnpackWords{}.pipe()
	PipeUnroll{}.pipe()
	PipeUpdate{}.pipe()

	// StatsFunc implementors.
	Count{}.statsFunc()
	Sum{}.statsFunc()
	Min{}.statsFunc()
	Max{}.statsFunc()
	Avg{}.statsFunc()
	Median{}.statsFunc()
	Quantile{}.statsFunc()
	Stddev{}.statsFunc()
	Stdvar{}.statsFunc()
	Rate{}.statsFunc()
	RateSum{}.statsFunc()
	CountUniq{}.statsFunc()
	CountUniqHash{}.statsFunc()
	UniqValues{}.statsFunc()
	FieldMax{}.statsFunc()
	FieldMin{}.statsFunc()
	JSONValues{}.statsFunc()
	Any{}.statsFunc()
	CountEmpty{}.statsFunc()
	SumLen{}.statsFunc()
	Values{}.statsFunc()
	Histogram{}.statsFunc()
	Last{}.statsFunc()
	First{}.statsFunc()
	RowAny{}.statsFunc()
	RowMax{}.statsFunc()
	RowMin{}.statsFunc()
	JSONValuesSorted{}.statsFunc()
	JSONValuesTopK{}.statsFunc()
}
