#!/usr/bin/env python3
"""Tie the compatibility matrix to the registry.

test/e2e-compat/compatibility-matrix.json lists the Loki, VictoriaLogs, Grafana
and Drilldown versions each track runs against. The registry says what is
actually proven. This joins them, so a version row carries the evidence behind
it instead of only a workflow name, and writes
conformance/reports/compatibility-matrix.md plus
conformance/registry/generated/matrix-link.json.

`--check` fails when a track names a score test that no longer exists, or when
a pinned version is not among the versions the matrix runs.

Usage: python3 conformance/scripts/matrix_link.py [--check]
"""
import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from registry_io import dump_json, load_json  # noqa: E402

ROOT = "conformance/registry"
MATRIX = "test/e2e-compat/compatibility-matrix.json"


def score_test_exists(name):
    found = subprocess.run(["grep", "-rl", f"func {name}(", "test", "internal"],
                           capture_output=True, text=True).stdout.strip()
    return found.split("\n")[0] if found else ""


def registry_totals():
    summary_path = os.path.join(ROOT, "generated/summary.json")
    summary = load_json(summary_path) if os.path.exists(summary_path) else {}
    evidence_path = os.path.join(ROOT, "generated/live-evidence.json")
    live = load_json(evidence_path) if os.path.exists(evidence_path) else {"cases": {}}
    holds = sum(1 for c in live["cases"].values() if c.get("verdict") == "holds")
    gaps = sum(1 for c in live["cases"].values() if c.get("verdict") == "gap")
    return summary, holds, gaps, live.get("recorded", "never")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    matrix = load_json(MATRIX)
    summary, holds, gaps, recorded = registry_totals()
    problems, rows = [], []
    for track, meta in matrix["tracks"].items():
        test = meta.get("score_test", "")
        where = score_test_exists(test) if test else ""
        if test and not where:
            problems.append(f"track {track}: score test {test} does not exist")
        rows.append({"track": track, "workflow": meta.get("workflow", "—"),
                     "score_test": test, "where": where,
                     "runtime_matrix": meta.get("runtime_matrix", False),
                     "edge_cases": len(meta.get("edge_cases", []))})
    versions = {}
    for component, meta in matrix["stack"].items():
        pinned = meta.get("pinned_version")
        listed = meta.get("matrix_versions", [])
        versions[component] = {"pinned": pinned, "matrix": listed}
        if pinned and listed and pinned not in listed:
            problems.append(f"{component}: pinned {pinned} is not in matrix_versions")

    dump_json(os.path.join(ROOT, "generated/matrix-link.json"),
              {"tracks": rows, "versions": versions,
               "registry": {"scores": summary.get("scores", {}),
                            "live_cases_hold": holds, "live_cases_gap": gaps,
                            "live_recorded": recorded}})

    lines = ["# Compatibility matrix", "",
             ("Generated by `conformance/scripts/matrix_link.py`. Versions come from "
              "`test/e2e-compat/compatibility-matrix.json`; the evidence columns come from the "
              "conformance registry."), "",
             "## Versions under test", "",
             "| Component | Pinned | Also tested |", "|---|---|---|"]
    for component, meta in sorted(versions.items()):
        also = ", ".join(v for v in meta["matrix"] if v != meta["pinned"]) or "—"
        lines.append(f"| {component} | `{meta['pinned'] or '—'}` | {also} |")
    lines += ["", "## Tracks and their evidence", "",
              "| Track | Workflow | Score test | Edge-case groups |", "|---|---|---|---:|"]
    for row in rows:
        test = f"`{row['score_test']}`" if row["score_test"] else "—"
        lines.append(f"| {row['track']} | `{row['workflow']}` | {test} | {row['edge_cases']} |")
    scores = summary.get("scores", {})
    lines += ["", "## Registry state behind the matrix", "",
              f"- Endpoints with a test comparing the proxy against Loki: "
              f"**{scores.get('coverage', 0):.0%}**",
              f"- Endpoints the proxy implements: **{scores.get('implementation', 0):.0%}**",
              f"- Implemented endpoints answered natively by VictoriaLogs: "
              f"**{scores.get('native_share_of_implemented', 0):.0%}**",
              f"- Live case proof, last run {recorded}: **{holds} hold**, **{gaps} gaps**", ""]
    os.makedirs("conformance/reports", exist_ok=True)
    with open("conformance/reports/compatibility-matrix.md", "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"conformance/reports/compatibility-matrix.md: {len(rows)} tracks, "
          f"{len(versions)} components, {len(problems)} problems")
    for line in problems:
        print("  " + line)
    if args.check and problems:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
