#!/usr/bin/env python3
"""Generate the compatibility roadmap from the registry's state.

What is proven, what is partial, what is a gap and what is waived are facts the
registry already holds. This renders them as the roadmap, so the plan and the
evidence cannot drift apart. Writes conformance/reports/roadmap.md.

Usage: python3 conformance/scripts/roadmap.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from registry_io import load_json, read_text  # noqa: E402

ROOT = "conformance/registry"
WEIGHT = {"explore": 3, "drilldown": 3, "datasource": 2, "api": 1}


def item_state(track, identifier):
    path = os.path.join(ROOT, "state", track, identifier + ".yaml")
    if not os.path.exists(path):
        return "unknown", ""
    text = read_text(path)
    state = re.search(r'^state:\s*(\S+)', text, re.M)
    reason = re.search(r'^reason: \|\n((?:\s+.*\n)+)', text, re.M)
    return (state.group(1) if state else "unknown",
            " ".join(reason.group(1).split()) if reason else "")


def collect(track, directory):
    items = []
    base = os.path.join(ROOT, directory)
    for name in sorted(os.listdir(base)) if os.path.isdir(base) else []:
        if not name.endswith(".yaml"):
            continue
        identifier = name[:-5]
        text = read_text(os.path.join(base, name))
        title = re.search(r'^title:\s*(.+)$', text, re.M)
        consumers = re.findall(r'^\s+- (\w+)$', re.search(
            r'consumers:\n((?:\s+- \w+\n)+)', text).group(1), re.M) \
            if re.search(r'consumers:\n', text) else []
        state, reason = item_state(track, identifier)
        items.append({"id": identifier, "title": title.group(1) if title else identifier,
                      "state": state, "reason": reason, "consumers": consumers,
                      "weight": sum(WEIGHT.get(c, 1) for c in consumers)})
    return items


def main():
    behaviours = collect("behaviours", "behaviours")
    translations = collect("translations", "translations")
    wiring_path = os.path.join(ROOT, "generated/wiring.json")
    wiring = load_json(wiring_path) if os.path.exists(wiring_path) else {"item_to_tests": {}}
    summary_path = os.path.join(ROOT, "generated/summary.json")
    summary = load_json(summary_path) if os.path.exists(summary_path) else {"scores": {}}

    everything = behaviours + translations
    by_state = {}
    for item in everything:
        by_state.setdefault(item["state"], []).append(item)

    lines = ["# Compatibility roadmap", "",
             ("Generated by `conformance/scripts/roadmap.py` from the registry's state. "
              "Do not edit by hand: change the state of an item, or prove it, and this "
              "follows."), "",
             "## Where we are", "",
             f"- Endpoints with a test comparing the proxy against Loki: "
             f"**{summary['scores'].get('coverage', 0):.0%}**",
             f"- Behaviour and feature items: "
             f"**{len(by_state.get('proven', []))} proven**, "
             f"{len(by_state.get('partial', []))} partial, "
             f"{len(by_state.get('gap', []))} gaps, "
             f"{len(by_state.get('waived', []))} waived", ""]

    for state, heading, blurb in (
        ("gap", "Next: unproven behaviour", "Ranked by which clients depend on it."),
        ("partial", "In progress", "Proven in part; the rest is named in the item's cases."),
        ("waived", "Accepted deviations", "Documented, with a rationale and an expiry."),
        ("proven", "Proven", "Held by at least one test that declares it."),
    ):
        items = sorted(by_state.get(state, []), key=lambda i: (-i["weight"], i["id"]))
        if not items:
            continue
        lines += ["", f"## {heading}", "", blurb, "",
                  "| Item | Consumers | Tests | Why |", "|---|---|---:|---|"]
        for item in items:
            tests = len(wiring["item_to_tests"].get(item["id"], []))
            lines.append(f"| `{item['id']}` — {item['title']} | "
                         f"{', '.join(item['consumers']) or '—'} | {tests} | "
                         f"{item['reason'][:120] or '—'} |")
    lines.append("")
    os.makedirs("conformance/reports", exist_ok=True)
    with open("conformance/reports/roadmap.md", "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"conformance/reports/roadmap.md: {len(everything)} items, "
          + ", ".join(f"{len(v)} {k}" for k, v in sorted(by_state.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
