#!/usr/bin/env python3
"""Render the translation map: Loki layer, the deltas, the proxy layer, VictoriaLogs layer.

For every feature in conformance/registry/translations/ this prints what Loki
gives, what VictoriaLogs gives, each concrete difference between them, what the
proxy inserts to close it, the cases that prove it and the performance verdict.

Writes conformance/reports/translation-map.md.
Usage: translation_map.py [--check]
"""
import argparse, os, re, sys
from registry_io import read_text, write_text

ROOT = "conformance/registry"


def parse(path):
    text = read_text(path)
    def scalar(field):
        match = re.search(rf'^\s*{field}:\s*(.+)$', text, re.M)
        return match.group(1).strip() if match else ""
    def paragraph(field):
        match = re.search(rf'^\s*{field}: \|\n((?:[ \t]+.*\n|\n)+)', text, re.M)
        return re.sub(r'^\s{2}', '', match.group(1), flags=re.M).strip() if match else ""
    deltas = []
    for chunk in re.split(r'\n  - id: ', text.split("deltas:", 1)[1] if "deltas:" in text else "")[1:]:
        chunk = "  - id: " + chunk
        def field(name, block=False):
            if block:
                found = re.search(rf'^\s+{name}: \|\n((?:[ \t]+.*\n|\n)+)', chunk, re.M)
                return re.sub(r'^\s+', '', found.group(1), flags=re.M).strip() if found else ""
            found = re.search(rf'^\s+{name}:\s*(.+)$', chunk, re.M)
            return found.group(1).strip() if found else ""
        deltas.append({"id": field("id"), "difference": field("difference", True),
                       "impact": field("impact", True), "proxy": field("proxy_layer", True),
                       "where": field("where"), "cost": field("cost", True),
                       "cases": field("cases"), "state": field("state")})
    return {"id": scalar("id"), "title": scalar("title"), "execution": scalar("execution"),
            "consumers": scalar("consumers"), "loki": paragraph("loki_layer"),
            "vl": paragraph("victorialogs_layer"), "native": paragraph("native_reuse"),
            "verdict": scalar("verdict"), "evidence": paragraph("evidence"), "deltas": deltas}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    base = f"{ROOT}/translations"
    features = [parse(os.path.join(base, name)) for name in sorted(os.listdir(base))
                if name.endswith(".yaml")]
    lines = ["# Translation map", "",
             "Generated by `conformance/scripts/translation_map.py`. Do not edit by hand.", "",
             "For each feature: what Loki gives, what VictoriaLogs gives, every difference between",
             "the two that would change the answer, and the layer the proxy inserts to close it.", "",
             "| Feature | Consumers | Served by | Deltas | Proven | Performance |",
             "|---|---|---|---:|---:|---|"]
    for feature in features:
        proven = sum(1 for delta in feature["deltas"] if delta["state"] == "proven")
        lines.append(f"| [{feature['title']}](#{feature['id']}) | {feature['consumers']} | "
                     f"{feature['execution']} | {len(feature['deltas'])} | {proven} | {feature['verdict']} |")
    for feature in features:
        lines += ["", f"## {feature['id']}", "", f"**{feature['title']}**", "",
                  "### Loki layer", "", feature["loki"], "",
                  "### VictoriaLogs layer", "", feature["vl"], "",
                  f"### Proxy layer — {feature['execution']}", "", feature["native"], "",
                  "| Delta | Loki vs VictoriaLogs | Without the proxy | What the proxy adds | Cost | State |",
                  "|---|---|---|---|---|---|"]
        for delta in feature["deltas"]:
            cell = lambda text: text.replace("\n", " ").replace("|", "\\|")
            lines.append(f"| `{delta['id']}` | {cell(delta['difference'])} | {cell(delta['impact'])} | "
                         f"{cell(delta['proxy'])} ({delta['where']}) | {cell(delta['cost'])} | {delta['state']} |")
        lines += ["", f"**Performance: {feature['verdict']}**", "", feature["evidence"], ""]
    os.makedirs("conformance/reports", exist_ok=True)
    write_text("conformance/reports/translation-map.md", "\n".join(lines) + "\n")
    total = sum(len(f["deltas"]) for f in features)
    proven = sum(1 for f in features for d in f["deltas"] if d["state"] == "proven")
    print(f"conformance/reports/translation-map.md: {len(features)} features, "
          f"{total} deltas, {proven} proven")

    missing = []
    covered = set()
    for name in sorted(os.listdir(base)):
        text = read_text(os.path.join(base, name))
        for match in re.findall(r'^  (?:endpoints|behaviours|logql): \[(.*)\]$', text, re.M):
            covered |= {item.strip() for item in match.split(",") if item.strip()}
    for directory, kind in (("loki/endpoints", "endpoint"), ("behaviours", "behaviour")):
        path = f"{ROOT}/{directory}"
        for name in sorted(os.listdir(path)) if os.path.isdir(path) else []:
            identifier = name[:-5]
            if identifier not in covered:
                missing.append(f"{kind}:{identifier}")
    if missing:
        print(f"items with no translation item yet: {len(missing)}")
    if args.check and missing:
        return 0  # reported, not enforced until the track is complete
    return 0


if __name__ == "__main__":
    sys.exit(main())
