#!/usr/bin/env python3
"""Append-only A/B history and the trend report built from it.

The daily run from main (daily.py) appends one line per shape set per day to
bench/ab/history/<set>.jsonl and regenerates bench/ab/history/trend.md. Docs
and plots read the JSONL; nothing edits past lines.

  history.py append SUMMARY.json [--commit SHA] [--dir bench/ab/history]
  history.py trend [--dir bench/ab/history] [--out bench/ab/history/trend.md]

A line holds the run's metadata and one row per shape x range in the column
order named by "cols" (so a line stays small and self-describing):

  {"date": "2026-09-24", "commit": "...", "baseline": "v1.93.0", "candidate": "main",
   "runs": 7, "valid": true, "cols": ["shape", "range", ...], "rows": [[...], ...]}

Columns: shape, range, status (candidate HTTP status), p50 and cold (candidate
warm p50 and first-run seconds), loki_p50, loki_cold, loki_status, parity
(candidate result vs Loki), base_p50 and verdict (vs the baseline build).
"""
import argparse
import datetime
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HISTORY = os.path.join(HERE, "history")
COLS = ["shape", "range", "status", "p50", "cold", "loki_p50", "loki_cold", "loki_status", "parity", "base_p50",
        "verdict"]
SPARK = "▁▂▃▄▅▆▇█"
# A day-over-day or week-over-week move is reported only beyond both.
NOISE, MIN_DELTA = 0.25, 0.05


def entry(summary, commit=""):
    c, r, b = summary["candidate"], summary["reference"], summary["baseline"]
    rows = []
    for row in summary["rows"]:
        rows.append([row["shape"], row["range"], row["status"].get(c), row["p50"].get(c), row["cold"].get(c),
                     row["p50"].get(r), row["cold"].get(r), row["status"].get(r),
                     row.get("parity_vs_reference", "n/a"), row["p50"].get(b), row["verdict"]])
    return {"date": summary["date"], "commit": commit, "set": summary["set"], "label": summary.get("label", ""),
            "baseline": b, "candidate": c, "reference": r, "runs": summary.get("runs"),
            "valid": summary.get("valid", True), "restarts": [summary.get("restart_before"), summary.get("restart_after")],
            "cols": COLS, "rows": rows}


def append(summary, directory=HISTORY, commit=""):
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, f"{summary['set']}.jsonl")
    line = entry(summary, commit)
    existing = read(path)
    if any(e["date"] == line["date"] and e.get("label") == line["label"] for e in existing):
        # One line per set per day: a re-run replaces nothing, it is skipped.
        return path, False
    with open(path, "a") as f:
        f.write(json.dumps(line, separators=(",", ":"), ensure_ascii=False) + "\n")
    return path, True


def read(path):
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return [json.loads(line) for line in f if line.strip()]


def rows_of(e):
    cols = e["cols"]
    return {(r[cols.index("shape")], r[cols.index("range")]): dict(zip(cols, r)) for r in e["rows"]}


def spark(values):
    vals = [v for v in values if v is not None]
    if len(vals) < 2:
        return ""
    lo, hi = min(vals), max(vals)
    span = hi - lo or 1
    return "".join(" " if v is None else SPARK[min(len(SPARK) - 1, int((v - lo) / span * (len(SPARK) - 1)))]
                   for v in values)


def moved(old, new):
    if old is None or new is None:
        return ""
    pct = (new - old) / old * 100 if old else 0
    if new > old * (1 + NOISE) and new - old > MIN_DELTA:
        icon = "🔴"
    elif new < old / (1 + NOISE) and old - new > MIN_DELTA:
        icon = "🟢"
    else:
        icon = "⚪"
    return f"{icon} {pct:+.0f}%"


def secs(v, status=None):
    if status not in (None, "200"):
        return f"**{status}**"
    if v is None:
        return "—"
    return f"{v * 1000:.0f} ms" if v < 1 else f"{v:.2f} s"


def previous(entries, days):
    """The newest valid entry at least `days` before the latest one."""
    latest = datetime.date.fromisoformat(entries[-1]["date"])
    for e in reversed(entries[:-1]):
        if e.get("valid", True) and (latest - datetime.date.fromisoformat(e["date"])).days >= days:
            return e
    return None


def trend(directory=HISTORY, window=14):
    lines = ["# Performance trend", "",
             "Generated by `bench/ab/history.py trend` from the daily A/B run on `main` "
             "(`bench/ab/daily.py`); do not edit. Each row is one query shape over one range on the same "
             "fresh stack and seeded data every day: the proxy built from `main` against Loki direct, warm p50 "
             f"(the first run is cold). Day and week columns compare with the previous run and the run seven "
             f"or more days earlier; a move counts only beyond {NOISE * 100:.0f}% and {MIN_DELTA * 1000:.0f} ms. "
             f"The sparkline is the last {window} runs of the proxy's warm p50.", ""]
    files = sorted(glob.glob(os.path.join(directory, "*.jsonl")))
    if not files:
        lines.append("No history yet.")
    for path in files:
        entries = [e for e in read(path)]
        if not entries:
            continue
        last = entries[-1]
        day, week = previous(entries, 1), previous(entries, 7)
        cur = rows_of(last)
        d_rows = rows_of(day) if day else {}
        w_rows = rows_of(week) if week else {}
        recent = entries[-window:]
        lines += [f"## {last['set']}", "",
                  f"Latest {last['date']} (`{(last.get('commit') or '?')[:10]}`, {last.get('runs')} runs"
                  f"{'' if last.get('valid', True) else ', **invalid: VictoriaLogs restarted**'}); "
                  f"previous {day['date'] if day else '—'}; week {week['date'] if week else '—'}.", "",
                  "| shape | range | proxy p50 | Δ day | Δ week | Loki p50 | proxy ÷ Loki | cold proxy / Loki | result vs Loki | trend |",
                  "|---|---|--:|--:|--:|--:|--:|--:|---|---|"]
        for key, row in cur.items():
            ratio = "—"
            if row["status"] == "200" and row["loki_status"] == "200" and row["p50"] and row["loki_p50"]:
                ratio = f"{row['p50'] / row['loki_p50']:.2f}×"
            d = d_rows.get(key, {}).get("p50") if d_rows.get(key, {}).get("status") == "200" else None
            w = w_rows.get(key, {}).get("p50") if w_rows.get(key, {}).get("status") == "200" else None
            series = [rows_of(e).get(key, {}).get("p50") for e in recent]
            parity = row["parity"] if row["parity"] != "n/a" else "—"
            lines.append(
                f"| {row['shape'].replace('|', chr(92) + '|')} | {row['range']} | {secs(row['p50'], row['status'])} | "
                f"{moved(d, row['p50']) if row['status'] == '200' else ''} | "
                f"{moved(w, row['p50']) if row['status'] == '200' else ''} | "
                f"{secs(row['loki_p50'], row['loki_status'])} | {ratio} | "
                f"{secs(row['cold'], row['status'])} / {secs(row['loki_cold'], row['loki_status'])} | {parity} | "
                f"{spark(series)} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("append")
    a.add_argument("summaries", nargs="+")
    a.add_argument("--commit", default="")
    a.add_argument("--dir", default=HISTORY)
    t = sub.add_parser("trend")
    t.add_argument("--dir", default=HISTORY)
    t.add_argument("--out", default=os.path.join(HISTORY, "trend.md"))
    args = ap.parse_args()
    if args.cmd == "append":
        for path in args.summaries:
            with open(path) as f:
                target, added = append(json.load(f), args.dir, args.commit)
            print(f"{'appended to' if added else 'already recorded in'} {target}")
    else:
        text = trend(args.dir)
        with open(args.out, "w") as f:
            f.write(text)
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
