apiVersion: v2
name: loki-vl-proxy
description: HTTP proxy translating Loki API to VictoriaLogs
type: application
version: 0.25.1
appVersion: "0.25.1"
home: https://github.com/szibis/Loki-VL-proxy
sources:
  - https://github.com/szibis/Loki-VL-proxy
keywords:
  - loki
  - victorialogs
  - proxy
  - logs
  - observability
maintainers:
  - name: szibis
