apiVersion: v2
name: loki-vl-proxy
description: HTTP proxy translating Loki API to VictoriaLogs
type: application
version: 1.32.2
appVersion: "1.32.2"
home: https://github.com/ReliablyObserve/Loki-VL-proxy
sources:
  - https://github.com/ReliablyObserve/Loki-VL-proxy
keywords:
  - loki
  - victorialogs
  - proxy
  - logs
  - observability
maintainers:
  - name: ReliablyObserve
