package config

// Limits describes every operator-tunable bound on the work one request may
// do, and the error a client receives when it is hit. Each entry names a flag
// declared in cmd/proxy/main.go; TestLimitsRegistryMatchesFlags fails when a
// flag disappears or a limit entry is missing its Helm value.
var Limits = []Limit{
	{
		Flag:       "backend-max-concurrent-heavy-queries",
		Unit:       "concurrent calls",
		Bounds:     "heavy VictoriaLogs calls running at once per replica: raw-row metric fetches above 10,000 rows, and stats, hits or unbounded query calls spanning at least -backend-heavy-query-min-range, finer than 11,000 buckets, or without a time range",
		Error:      "429 `too many outstanding requests: heavy VictoriaLogs queries are limited to -backend-max-concurrent-heavy-queries=N per replica and this query waited -backend-heavy-query-queue-wait=D`",
		Metric:     "loki_vl_proxy_internal_operation_total{operation=\"backend_heavy_query_admission\"}",
		Alert:      "none",
		LokiParity: "querier.max_concurrent / the query scheduler queue (Loki answers a full queue with the same 429 message)",
		Sizing:     "VictoriaLogs lets each stats pipe of one query use up to 40% of -memory.allowedPercent, so 2 keeps concurrent stats state inside its budget. Raise it with VictoriaLogs memory (the fleet total is replicas x this value); lower it to 1 for a VictoriaLogs under 2 GiB.",
	},
	{
		Flag:       "backend-heavy-query-queue-wait",
		Unit:       "duration",
		Bounds:     "how long the heavy calls of one request wait, in total, for an admission slot",
		Error:      "429 `too many outstanding requests` naming both admission flags",
		Metric:     "loki_vl_proxy_internal_operation_duration_seconds{operation=\"backend_heavy_query_admission\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Keep it below the Grafana data source timeout (30s by default) so a queued panel fails with the documented 429 instead of a client timeout. Raise it when dashboards have more heavy panels than slots; lower it to shed load earlier.",
	},
	{
		Flag:       "backend-heavy-query-min-range",
		Unit:       "duration",
		Bounds:     "the time range from which stats, hits and unbounded raw calls count as heavy",
		Error:      "none directly; it selects which calls the admission limiter governs",
		Metric:     "loki_vl_proxy_internal_operation_total{operation=\"backend_heavy_query_admission\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Lower it (for example 1h) when short ranges already strain VictoriaLogs; raise it when only multi-day queries need queueing.",
	},
	{
		Flag:       "manual-range-metric-row-limit",
		Unit:       "rows",
		Bounds:     "rows one proxy-side range-metric evaluation reads: raw log rows, or stats rows (one per non-empty step bucket and series) per bucket grid on the window stats path",
		Error:      "502 `manual range metric row limit exceeded (N); narrow the query or increase -manual-range-metric-row-limit`",
		Metric:     "loki_vl_proxy_requests_total{status=\"502\"}",
		Alert:      "LokiVLProxyHighErrorRate (any sustained 5xx)",
		LokiParity: "",
		PerTenant:  false,
		Sizing:     "Proxy memory is about 100 bytes per stats row and about 32 bytes per raw sample, so the default bounds one evaluation to roughly 100 MiB. Raise it for high-cardinality groupings over days; lower it to reject expensive scans earlier.",
	},
	{
		Flag:       "max-stats-query-series",
		Unit:       "series",
		Bounds:     "series in the result of a metric query, on every metric route, range and instant; per tenant as max_query_series in -tenant-limits and -tenant-default-limits, published on /loki/api/v1/drilldown-limits and /config/tenant/v1/limits",
		Error:      "400 `maximum number of series (N) reached for a single query; consider reducing query cardinality ...` (Loki's text); a Logs Drilldown request gets 200 with the busiest N series and the warning `maximum number of series (N) reached for a single query; returning partial results`",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "LokiVLProxyHighClientErrors",
		LokiParity: "max_query_series (500); a multi-tenant request is held to the smallest of its tenants",
		PerTenant:  true,
		Sizing:     "500 matches Loki's default and the Drilldown series cap. Raise it for dashboards that legitimately render thousands of series, at the cost of response size and browser rendering; topk and bottomk rank every series regardless of this cap. Raise `-backend-max-buffered-response-bytes` with it: this cap is what usually keeps a result inside the byte budget, so raising it alone converts Loki's series-limit error into `manual metric response exceeds N bytes`. Budget about 40 bytes per sample plus about 100 bytes per series - series x steps x 40 bytes - so 64 MiB holds roughly 1,500 dense series over a 1,000-step range. On the e2e stack `sum by (pod) (rate({service_name=\"api-gateway\"}[5m]))` over 7d covers about 240,000 distinct pods: at the 500 default it answers 491 series in 0.5s, and at 1,000,000 it exceeds 64 MiB and returns 502.",
	},
	{
		Flag:       "ordered-json-metric-max-bytes",
		Unit:       "bytes",
		Bounds:     "bytes the ordered JSON metric evaluator reads from the raw rows response, and the largest response it builds",
		Error:      "502 `ordered JSON metric response exceeds N bytes; narrow the query or increase -ordered-json-metric-max-bytes`",
		Metric:     "loki_vl_proxy_requests_total{status=\"502\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "The default admits about one million rows of 1 KiB. Rows are streamed, so raising it costs VictoriaLogs scan work and network transfer rather than proxy memory; lower it to protect VictoriaLogs from long raw scans.",
	},
	{
		Flag:       "backend-max-buffered-response-bytes",
		Unit:       "bytes",
		Bounds:     "bytes read from one VictoriaLogs response the proxy evaluates itself: buffered stats, volume and binary-operand responses, and the encoded metric result",
		Error:      "502 `manual metric response exceeds N bytes; narrow the query or increase -backend-max-buffered-response-bytes`",
		Metric:     "loki_vl_proxy_requests_total{status=\"502\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Proxy memory grows with this value times the requests that buffer a response at once, so treat it as per-request memory: 64 MiB x -max-concurrent is the worst case. Raise it for very wide stats responses; lower it on small replicas. It is the second half of `-max-stats-query-series`: the series cap decides how many series a result may carry, this decides whether the encoded result fits. Raising either one alone moves the failure rather than removing it - a high series cap with the default byte budget fails with `manual metric response exceeds N bytes` instead of the series-limit error. Size it as series x steps x 40 bytes for the widest chart you intend to serve, then check the replica has that much memory per concurrent request.",
	},
	{
		Flag:       "max-entries-limit-per-query",
		Unit:       "rows",
		Bounds:     "log lines a log query may ask for (Loki's max_entries_limit_per_query, per tenant in -tenant-limits and -tenant-default-limits, where 0 is unlimited); label values requests above it are capped",
		Error:      "400 `max entries limit per query exceeded, limit > max_entries_limit_per_query (L > N)` (Loki's text); with -max-entries-limit-per-query-cap the limit is lowered to N instead",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "LokiVLProxyHighClientErrors",
		LokiParity: "max_entries_limit_per_query (Loki's default is 5000; the proxy keeps 10000); a multi-tenant request is held to the smallest non-zero value of its tenants",
		PerTenant:  true,
		Sizing:     "Raise it for clients that ask for more log lines per request; lower it towards Loki's 5000 to bound response size. Grafana asks for its Max lines setting (1000 by default), well below the default.",
	},
	{
		Flag:       "max-query-length-bytes",
		Unit:       "bytes",
		Bounds:     "the LogQL query string length",
		Error:      "400 `query exceeds max length (N > M); raise -max-query-length-bytes`",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "LokiVLProxyHighClientErrors",
		LokiParity: "syntax.maxInputSize (131072): the default matches it, so the proxy rejects only what Loki rejects",
		Sizing:     "Lower it to reject generated queries earlier; raising it above Loki's own limit has no effect, because Loki's parse error fires first.",
	},
	{
		Flag:       "default-max-query-length",
		Unit:       "duration",
		Bounds:     "the query time range accepted for every tenant unless a per-tenant limit overrides it",
		Error:      "400 `the query time range exceeds the limit (query length: X, limit: Y)`",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "LokiVLProxyHighClientErrors",
		LokiParity: "max_query_length (Loki's default is 721h; the proxy keeps 0, unlimited); a multi-tenant request is held to the smallest non-zero value of its tenants",
		PerTenant:  true,
		Sizing:     "Set it to the retention you want users to query; per-tenant limits in -tenant-limits override it.",
	},
	{
		Flag:       "multi-tenant-max-fanout",
		Unit:       "tenants",
		Bounds:     "tenants one multi-tenant request may fan out to",
		Error:      "400 `multi-tenant fanout exceeds limit of N tenants; raise -multi-tenant-max-fanout or query fewer tenants`",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "LokiVLProxyHighClientErrors",
		LokiParity: "",
		Sizing:     "Each tenant in the list is a separate backend query, so this multiplies every other limit. Raise it only with matching VictoriaLogs capacity.",
	},
	{
		Flag:       "multi-tenant-max-merged-response-bytes",
		Unit:       "bytes",
		Bounds:     "the merged response of a multi-tenant request",
		Error:      "413 `multi-tenant merged response exceeds configured safety limit; raise -multi-tenant-max-merged-response-bytes or query fewer tenants`",
		Metric:     "loki_vl_proxy_requests_total{status=\"413\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "The merged body is held in proxy memory once per request; size it with -multi-tenant-max-fanout and replica memory.",
	},
	{
		Flag:       "binary-metric-max-operand-bytes",
		Unit:       "bytes",
		Bounds:     "operand bytes one binary metric expression may capture",
		Error:      "400 `binary expression exceeds its evaluation budget`",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Raise it for wide binary expressions over many series; the bytes are held in proxy memory for the request.",
	},
	{
		Flag:       "binary-metric-max-arrays",
		Unit:       "arrays",
		Bounds:     "JSON arrays one binary metric expression may allocate while joining operands",
		Error:      "400 `binary expression exceeds its evaluation budget`",
		Metric:     "loki_vl_proxy_requests_total{status=\"400\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Raise it together with -binary-metric-max-operand-bytes; both bound one request's peak allocation.",
	},
	{
		Flag:       "detected-fields-max-scan-lines",
		Unit:       "rows",
		Bounds:     "log lines the detected_fields and detected_field values scan reads per request",
		Error:      "none: the scan stops at the limit and returns what it found",
		Metric:     "none",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Raise it when Drilldown misses fields that appear late in a window, at the cost of a longer VictoriaLogs scan; -drilldown-scan-timeout still bounds the time.",
	},
	{
		Flag:       "patterns-max-backend-rows",
		Unit:       "rows",
		Bounds:     "log lines /patterns reads from VictoriaLogs for one request",
		Error:      "none: pattern mining works on the rows it read",
		Metric:     "loki_vl_proxy_patterns_lines_scanned_total",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Raise it for sparse selectors where patterns are mined from too few lines; every extra row is VictoriaLogs scan work and proxy parsing.",
	},
	{
		Flag:       "patterns-second-pass-max-rows",
		Unit:       "rows",
		Bounds:     "log lines the /patterns second pass reads when the first pass mined too few patterns",
		Error:      "none",
		Metric:     "loki_vl_proxy_patterns_lines_scanned_total",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Raise it with -patterns-max-backend-rows; the second pass doubles the scan for hard selectors.",
	},
	{
		Flag:       "patterns-second-pass-max-windows",
		Unit:       "windows",
		Bounds:     "windows the /patterns second pass re-reads",
		Error:      "none",
		Metric:     "none",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Each window is one VictoriaLogs call; raise it only when pattern coverage over long ranges matters more than fanout.",
	},
	{
		Flag:       "drilldown-max-stats-buckets",
		Unit:       "buckets",
		Bounds:     "time buckets one Grafana Logs Drilldown stats call may request; finer steps are coarsened to fit",
		Error:      "none: the step is coarsened",
		Metric:     "none",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Raise it for finer Drilldown charts at the cost of VictoriaLogs memory (buckets x series are built in memory before the response); lower it to protect a small backend.",
	},
	{
		Flag:       "max-zero-fill-buckets",
		Unit:       "buckets",
		Bounds:     "buckets the proxy zero-fills in a metric response",
		Error:      "none: a wider request is served without zero-fill",
		Metric:     "none",
		Alert:      "none",
		LokiParity: "the 11,000-point resolution limit bounds a Loki response anyway",
		Sizing:     "Rarely needs changing; it only bounds proxy-side allocation for zero-filled charts.",
	},
	{
		Flag:       "stats-query-range-concurrency",
		Unit:       "concurrent calls",
		Bounds:     "concurrent stats_query_range calls the proxy makes to VictoriaLogs",
		Error:      "none: calls wait for a slot",
		Metric:     "loki_vl_proxy_upstream_requests_total{route=\"/select/logsql/stats_query_range\"}",
		Alert:      "none",
		LokiParity: "",
		Sizing:     "Drilldown Fields fires about 30 of these at once; 4 keeps VictoriaLogs CPU steady. Heavy calls are additionally bounded by -backend-max-concurrent-heavy-queries.",
	},
	{
		Flag:       "max-concurrent",
		Unit:       "requests",
		Bounds:     "requests admitted per replica, and concurrent backend operations",
		Error:      "503 `too many concurrent queries` with `Retry-After: 5`",
		Metric:     "loki_vl_proxy_requests_total{status=\"503\"}",
		Alert:      "LokiVLProxyHighErrorRate",
		LokiParity: "",
		Sizing:     "Size it with replica CPU and VictoriaLogs capacity; 0 disables admission entirely, which lets one client drive unbounded fanout.",
	},
	{
		Flag:       "max-lines",
		Unit:       "rows",
		Bounds:     "the default number of log lines per query when the client sends no limit",
		Error:      "none",
		Metric:     "none",
		Alert:      "none",
		LokiParity: "the Loki data source's Max lines (1000)",
		PerTenant:  true,
		Sizing:     "Raise it only with -max-entries-limit-per-query; every line is transferred and rendered.",
	},
}
