package config

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// limitRecord is one limit as the conformance registry consumes it: the flag as
// the binary declares it, plus the operator metadata this package adds.
type limitRecord struct {
	Flag       string `json:"flag"`
	HelmValue  string `json:"helm_value"`
	Type       string `json:"type"`
	Default    string `json:"default"`
	Unit       string `json:"unit"`
	Bounds     string `json:"bounds"`
	Error      string `json:"error"`
	Metric     string `json:"metric"`
	Alert      string `json:"alert"`
	LokiParity string `json:"loki_parity"`
	PerTenant  bool   `json:"per_tenant"`
	Sizing     string `json:"sizing"`
}

type limitsDocument struct {
	Source string        `json:"source"`
	Note   string        `json:"note"`
	Limits []limitRecord `json:"limits"`
}

// RenderLimitsJSON exports the limits registry for the conformance registry, so
// the inventory of operator-tunable bounds is generated from the same source as
// the documentation instead of being maintained twice.
func RenderLimitsJSON(flags []Flag) (string, error) {
	byName := map[string]Flag{}
	for _, f := range flags {
		byName[f.Name] = f
	}
	document := limitsDocument{
		Source: "internal/config (flags parsed from " + MainGoPath + ")",
		Note: "Generated by `go run ./cmd/configdoc`. The conformance registry reads this file; " +
			"do not maintain a second list of limits by hand.",
		Limits: make([]limitRecord, 0, len(Limits)),
	}
	for _, limit := range Limits {
		flag, ok := byName[limit.Flag]
		if !ok {
			return "", fmt.Errorf("limits registry: flag -%s is not declared by the binary", limit.Flag)
		}
		document.Limits = append(document.Limits, limitRecord{
			Flag:       limit.Flag,
			HelmValue:  HelmKeyOf(limit.Flag),
			Type:       flag.Type,
			Default:    flag.Default,
			Unit:       limit.Unit,
			Bounds:     limit.Bounds,
			Error:      limit.Error,
			Metric:     limit.Metric,
			Alert:      limit.Alert,
			LokiParity: limit.LokiParity,
			PerTenant:  limit.PerTenant,
			Sizing:     limit.Sizing,
		})
	}
	var buffer bytes.Buffer
	encoder := json.NewEncoder(&buffer)
	encoder.SetIndent("", "  ")
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(document); err != nil {
		return "", err
	}
	return buffer.String(), nil
}
