package config

import (
	"fmt"
	"sort"
	"strings"
)

const generatedHeader = "> Generated by `go run ./cmd/configdoc` from the flags in `cmd/proxy/main.go` and the registry in `internal/config`. Do not edit by hand.\n\n"

// escapeCell makes a description safe inside a Markdown table cell that MDX
// also parses: pipes end the cell, and braces or angle brackets outside code
// spans would be read as JSX.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.Join(strings.Fields(s), " ")
	parts := strings.Split(s, "`")
	for i := range parts {
		if i%2 == 1 { // inside a code span: MDX leaves it alone
			continue
		}
		parts[i] = strings.NewReplacer("{", "&#123;", "}", "&#125;", "<", "&lt;", ">", "&gt;").Replace(parts[i])
	}
	return strings.Join(parts, "`")
}

func defaultCell(f Flag) string {
	def := strings.TrimSpace(f.Default)
	if def == `""` || def == "" {
		return "(empty)"
	}
	return "`" + def + "`"
}

// RenderConfigurationReference lists every flag by category.
func RenderConfigurationReference(flags []Flag) string {
	byCategory := map[string][]Flag{}
	for _, f := range flags {
		byCategory[CategoryOf(f.Name)] = append(byCategory[CategoryOf(f.Name)], f)
	}
	names := make([]string, 0, len(byCategory))
	for name := range byCategory {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Configuration reference\n\n")
	fmt.Fprintf(&b, "Every command-line flag of the proxy (%d), grouped by category, with the Helm value that sets it. Narrative guidance lives in [configuration.md](../configuration.md); the bounds on work are collected in [limits-registry.md](limits-registry.md).\n\n", len(flags))
	b.WriteString("Helm passes any flag through `extraArgs.<flag>`; the chart sets a few of them from dedicated values, marked chart-managed.\n")
	for _, name := range names {
		b.WriteString("\n## " + name + "\n\n")
		b.WriteString("| Flag | Type | Default | Helm value | Description |\n|---|---|---|---|---|\n")
		for _, f := range byCategory[name] {
			fmt.Fprintf(&b, "| `-%s` | %s | %s | `%s` | %s |\n", f.Name, strings.ToLower(f.Type), defaultCell(f), HelmKeyOf(f.Name), escapeCell(f.Usage))
		}
	}
	return b.String()
}

// RenderLimitsRegistry documents every bound on work.
func RenderLimitsRegistry(flags []Flag) (string, error) {
	byName := map[string]Flag{}
	for _, f := range flags {
		byName[f.Name] = f
	}
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Limits registry\n\n")
	b.WriteString("Every operator-tunable bound on the work one request may do. A limit is never a silent truncation: hitting one returns an error that names the flag, so an operator can raise it. Zero selects the built-in default of each flag; startup rejects negative values.\n\n")
	b.WriteString("Fleet arithmetic: per-replica limits multiply by the replica count, and every byte limit multiplies by the requests that hold a response at once (`-max-concurrent`).\n\n")
	b.WriteString("| Limit | Flag | Helm value | Default | Unit | Bounds | Error when hit | Metric | Alert | Per tenant | Loki parity |\n|---|---|---|---|---|---|---|---|---|---|---|\n")
	for _, limit := range Limits {
		flag, ok := byName[limit.Flag]
		if !ok {
			return "", fmt.Errorf("limits registry: flag -%s is not declared by the binary", limit.Flag)
		}
		perTenant := "no"
		if limit.PerTenant {
			perTenant = "yes (`-tenant-limits`)"
		}
		parity := limit.LokiParity
		if parity == "" {
			parity = "proxy-specific"
		}
		fmt.Fprintf(&b, "| %s | `-%s` | `%s` | %s | %s | %s | %s | %s | %s | %s | %s |\n",
			escapeCell(strings.ReplaceAll(limit.Flag, "-", " ")), limit.Flag, HelmKeyOf(limit.Flag), defaultCell(flag), limit.Unit,
			escapeCell(limit.Bounds), escapeCell(limit.Error), escapeCell(limit.Metric), escapeCell(limit.Alert), perTenant, escapeCell(parity))
	}
	b.WriteString("\n## Sizing\n\n")
	for _, limit := range Limits {
		fmt.Fprintf(&b, "### `-%s`\n\n%s\n\n", limit.Flag, strings.TrimSpace(limit.Sizing))
	}
	b.WriteString("## Worked examples\n\n")
	b.WriteString(smallDeploymentExample)
	b.WriteString(largeDeploymentExample)
	return b.String(), nil
}

// RenderErrorsAndAlerts indexes errors and alerts back to their limit.
func RenderErrorsAndAlerts(flags []Flag) (string, error) {
	byName := map[string]Flag{}
	for _, f := range flags {
		byName[f.Name] = f
	}
	type row struct{ message, flag, fix string }
	var rows []row
	for _, limit := range Limits {
		if strings.HasPrefix(limit.Error, "none") {
			continue
		}
		flag := byName[limit.Flag]
		rows = append(rows, row{limit.Error, limit.Flag, fmt.Sprintf("%s Default %s.", strings.TrimSpace(limit.Sizing), strings.Trim(defaultCell(flag), "`"))})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].message < rows[j].message })

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Errors and alerts index\n\n")
	b.WriteString("What a client error or a firing alert means, which limit produced it, and how to change that limit.\n\n")
	b.WriteString("## Errors\n\n| Response | Limit that produced it | What to do |\n|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | `-%s` | %s |\n", escapeCell(r.message), r.flag, escapeCell(r.fix))
	}
	b.WriteString("\n## Alerts\n\n| Alert | Limits that can fire it |\n|---|---|\n")
	byAlert := map[string][]string{}
	for _, limit := range Limits {
		if limit.Alert == "none" || limit.Alert == "" {
			continue
		}
		byAlert[limit.Alert] = append(byAlert[limit.Alert], "`-"+limit.Flag+"`")
	}
	alerts := make([]string, 0, len(byAlert))
	for alert := range byAlert {
		alerts = append(alerts, alert)
	}
	sort.Strings(alerts)
	for _, alert := range alerts {
		fmt.Fprintf(&b, "| %s | %s |\n", escapeCell(alert), strings.Join(byAlert[alert], ", "))
	}
	b.WriteString("\nAlerts without a limit in this index (backend reachability, latency, memory, cache hit rate) report the health of the proxy or of VictoriaLogs, not a configured bound. See [alerting](../../alerting/loki-vl-proxy-alerting-rules.yaml).\n")
	return b.String(), nil
}

const smallDeploymentExample = "### A small deployment\n\n" +
	"One proxy replica with 512 MiB, one VictoriaLogs with 2 GiB, a handful of Grafana users:\n\n" +
	"```yaml\n" +
	"extraArgs:\n" +
	"  backend-max-concurrent-heavy-queries: \"1\"   # one heavy stats state fits in VictoriaLogs memory\n" +
	"  backend-heavy-query-queue-wait: \"25s\"       # still below Grafana's 30s data source timeout\n" +
	"  backend-max-buffered-response-bytes: \"16777216\"  # 16 MiB per buffered response\n" +
	"  manual-range-metric-row-limit: \"250000\"     # about 25 MiB of proxy-side samples\n" +
	"  max-concurrent: \"16\"\n" +
	"```\n\n"

const largeDeploymentExample = "### A large, high-volume deployment\n\n" +
	"Three proxy replicas with 4 GiB each, VictoriaLogs with 64 GiB, dashboards over days:\n\n" +
	"```yaml\n" +
	"extraArgs:\n" +
	"  backend-max-concurrent-heavy-queries: \"6\"   # 18 heavy calls fleet-wide; VictoriaLogs has the memory for them\n" +
	"  backend-heavy-query-queue-wait: \"20s\"\n" +
	"  backend-heavy-query-min-range: \"12h\"        # only long ranges queue\n" +
	"  backend-max-buffered-response-bytes: \"268435456\"  # 256 MiB for wide stats responses\n" +
	"  manual-range-metric-row-limit: \"4000000\"    # high-cardinality groupings over 7d\n" +
	"  max-stats-query-series: \"5000\"\n" +
	"  max-concurrent: \"256\"\n" +
	"```\n"
